import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "@/components/layout-helper/LayoutWrapper";
import { Manrope, Mukta, Rozha_One } from "next/font/google";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
});

const mukta = Mukta({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-mukta",
});

const rozha = Rozha_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-rozha",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html
      lang="en"
      className={`${manrope.variable} ${mukta.variable} ${rozha.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#0D0D0D] text-[#F5F1EB] bg-dot-pattern">
        <LayoutWrapper>
        <div className="fixed inset-0 pointer-events-none z-50 opacity-[0.1] noise" />
          {children}
        </LayoutWrapper>
        </body>
    </html>
  );
}
